<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('workout_sets', function (Blueprint $table) {
            // Idempotency key generated by the client for each "add set" attempt.
            // Lets retried requests (flaky mobile connections) return the
            // already-created set instead of inserting a duplicate.
            $table->string('client_request_id', 64)->nullable()->after('reps');
            $table->unique('client_request_id');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('workout_sets', function (Blueprint $table) {
            $table->dropUnique(['client_request_id']);
            $table->dropColumn('client_request_id');
        });
    }
};
